// <copyright file="GlobalSuppressions.cs" company="TheCrownProsecutionService">
// Copyright (c) The Crown Prosecution Service. All rights reserved.
// </copyright>

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "Status is not a member of GetCaseMaterials class, but rather a property of the Communication object", Scope = "member", Target = "~M:Cps.Fct.Djb.TransferToolApi.GetCaseMaterials.UpdateCommunicationsStatus(System.Collections.Generic.IReadOnlyCollection{Cps.Fct.Hk.Ui.Interfaces.Model.Communication},Cps.Fct.Hk.Ui.Interfaces.Model.UnusedMaterialsResponse,Cps.Fct.Hk.Ui.Interfaces.Model.UsedStatementsResponse,Cps.Fct.Hk.Ui.Interfaces.Model.UsedExhibitsResponse)~System.Collections.Generic.List{Cps.Fct.Hk.Ui.Interfaces.Model.Communication}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "For easier testability", Scope = "member", Target = "~M:Cps.Fct.Djb.TransferToolApi.GetCaseMaterials.UpdateCommunicationsStatus(System.Collections.Generic.IReadOnlyCollection{Cps.Fct.Hk.Ui.Interfaces.Model.Communication},Cps.Fct.Hk.Ui.Interfaces.Model.UnusedMaterialsResponse,Cps.Fct.Hk.Ui.Interfaces.Model.UsedStatementsResponse,Cps.Fct.Hk.Ui.Interfaces.Model.UsedExhibitsResponse)~System.Collections.Generic.List{Cps.Fct.Hk.Ui.Interfaces.Model.Communication}")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1010:Opening square brackets should be spaced correctly", Justification = "Spacing is allowed for tags.")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1011:Closing square brackets should be spaced correctly", Justification = "Conflicts with different warning", Scope = "member", Target = "~M:Cps.Fct.Djb.TransferToolApi.Program.Main(System.String[])")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "For easier testability", Scope = "member", Target = "~M:Cps.Fct.Djb.TransferToolApi.GetCaseMaterials.MapCommunicationsToCaseMaterials(System.Collections.Generic.IEnumerable{Cps.Fct.Hk.Ui.Interfaces.Model.Communication})~System.Collections.Generic.List{Cps.Fct.Hk.Ui.Interfaces.Model.CaseMaterial}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "For easier testability", Scope = "member", Target = "~M:Cps.Fct.Djb.TransferToolApi.GetCaseMaterials.MapUsedExhibitsToCaseMaterials(Cps.Fct.Hk.Ui.Interfaces.Model.UsedExhibitsResponse)~System.Collections.Generic.List{Cps.Fct.Hk.Ui.Interfaces.Model.CaseMaterial}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "For easier testability", Scope = "member", Target = "~M:Cps.Fct.Djb.TransferToolApi.GetCaseMaterials.MapUsedStatementsToCaseMaterials(Cps.Fct.Hk.Ui.Interfaces.Model.UsedStatementsResponse)~System.Collections.Generic.List{Cps.Fct.Hk.Ui.Interfaces.Model.CaseMaterial}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "For easier testability", Scope = "member", Target = "~M:Cps.Fct.Djb.TransferToolApi.GetCaseMaterials.MapUnusedMaterialsToCaseMaterials(Cps.Fct.Hk.Ui.Interfaces.Model.UnusedMaterialsResponse)~System.Collections.Generic.List{Cps.Fct.Hk.Ui.Interfaces.Model.CaseMaterial}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "For easier testability", Scope = "member", Target = "~M:Cps.Fct.Djb.TransferToolApi.GetCaseMaterials.ConfigureResponseHeaders(Microsoft.AspNetCore.Http.HttpResponse)")]
