trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  nugetFeed: 'cps-fct-hk'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: Restore projects
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: build package
  inputs:
    command: 'build'
    projects: '**/common/**/*.csproj' 
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Pack libraries
  inputs:
    command: 'pack'
    packagesToPack: '**/common/**/*.csproj'   
    configuration: '$(buildConfiguration)'
    outputDirectory: '$(Build.ArtifactStagingDirectory)/nuget'
    arguments: '--include-symbols --include-source'

- task: NuGetCommand@2
  displayName: Push package
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'Case Housekeeping/cps-fct-hk'
