// <copyright file="GlobalSuppressions.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1124:Do not use regions", Justification = "Needed for test arrangement", Scope = "member", Target = "~M:Cps.Fct.Hk.Ui.ServiceClient.Ddei.Tests.ApiServiceClientTests.EnsureAuthenticationHeaders_ShouldAddHeaders_WhenValidInputsProvided")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1124:Do not use regions", Justification = "Needed for test arrangement", Scope = "member", Target = "~M:Cps.Fct.Hk.Ui.ServiceClient.Ddei.Tests.ApiServiceClientTests.GetCmsModernTokenAsync_ThrowsArgumentException_WhenRequestIsNull~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1124:Do not use regions", Justification = "Needed for test arrangement", Scope = "member", Target = "~M:Cps.Fct.Hk.Ui.ServiceClient.Ddei.Tests.ApiServiceClientTests.ListCommunicationsHkAsync_ThrowsArgumentException_WhenRequestIsNull~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1124:Do not use regions", Justification = "Needed for test arrangement", Scope = "member", Target = "~M:Cps.Fct.Hk.Ui.ServiceClient.Ddei.Tests.ApiServiceClientTests.GetCaseSummaryAsync_ReturnsCaseSummary_WhenResponseIsSuccessful~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1124:Do not use regions", Justification = "Needed for test arrangement", Scope = "member", Target = "~M:Cps.Fct.Hk.Ui.ServiceClient.Ddei.Tests.ApiServiceClientTests.ReclassifyCommunicationAsync_ValidRequest_ReturnsExpectedResponse_ShouldLogCorrectly~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1124:Do not use regions", Justification = "Needed for test arrangement", Scope = "member", Target = "~M:Cps.Fct.Hk.Ui.ServiceClient.Ddei.Tests.ApiServiceClientTests.GetUsedStatementsAsync_ThrowsArgumentException_WhenRequestIsNull~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1124:Do not use regions", Justification = "Needed for test arrangement", Scope = "member", Target = "~M:Cps.Fct.Hk.Ui.ServiceClient.Ddei.Tests.ApiServiceClientTests.GetUsedExhibitsAsync_ThrowsArgumentException_WhenRequestIsNull~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1124:Do not use regions", Justification = "Needed for test arrangement", Scope = "member", Target = "~M:Cps.Fct.Hk.Ui.ServiceClient.Ddei.Tests.ApiServiceClientTests.GetUnusedMaterialsAsync_ThrowsArgumentException_WhenRequestIsNull~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1124:Do not use regions", Justification = "Needed for test arrangement", Scope = "member", Target = "~M:Cps.Fct.Hk.Ui.ServiceClient.Ddei.Tests.ApiServiceClientTests.GetMaterialDocumentAsync_Success_ReturnsFileStreamResult~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1124:Do not use regions", Justification = "Needed for test arrangement", Scope = "member", Target = "~M:Cps.Fct.Hk.Ui.ServiceClient.Ddei.Tests.ApiServiceClientTests.GetMaterialDocumentAsync_Success_ReturnsDefaultFileStreamResult~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1124:Do not use regions", Justification = "Needed for test arrangement", Scope = "member", Target = "~M:Cps.Fct.Hk.Ui.ServiceClient.Ddei.Tests.ApiServiceClientTests.GetAttachmentsAsync_ThrowsArgumentException_WhenRequestIsNull~System.Threading.Tasks.Task")]
